---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}


library(rgrass7)
library(sf)
library(tidyverse)
library(raster)


source("D:/LUCA Team/Land Use Capability Assessments Limited/LUCA Directors - Documents/Code/RCode/ligrab/ligrab_utilities.R")


setwd(coderoot)
getwd()
grass_env_code_ffn =   file.path(getwd(), 'env_scripts', 'grass_env.R')
file.exists(grass_env_code_ffn)

source(file = grass_env_code_ffn)

library(rgrass7)

initGRASS(gisBase  = file.path('C:', 'OSGeo4W64', 'apps', 'grass', 'grass78'),
          gisDbase = file.path('D:', 'Grass'),  location = 'ligrab', 
          mapset   = "PERMANENT", override = TRUE)


# library(rgrass7)

Sys.setenv('SAGA' = file.path(Sys.getenv('OSGEO4W_ROOT'), 'apps', 'saga-ltr'))
Sys.setenv('PATH' = paste(Sys.getenv("PATH"),
                          file.path(Sys.getenv('SAGA')),
                          file.path(Sys.getenv('SAGA'), 'modules'),
                          sep = .Platform$path.sep))


```


```{r}

dataroot = "D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/2021-07-10-LP0038-R_Hart/"

# dataroot = "D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/Development Projects/DP-0046-ligrab-R-Development/"



```




```{r}


gis_dir = paste0(dataroot,"gis/")
if (!dir.exists(gis_dir)){dir.create(gis_dir)}


lig_dir = paste0(gis_dir,"layers/")
if (!dir.exists(lig_dir)){dir.create(lig_dir)}

# 
# setwd(wkg_dir)
# getwd()  


  "orthophoto",
  "catchment",
  "landcover",
  "soil",
  "geology",
  "elevation",
  "localauthorities",
  "climate",
options(stringsAsFactors = FALSE, scipen = 999)
# library(raster)
# library(sf)


ligrab_subdirs = c(
  "cadastral",
  "derived",
  "LUC",
  "LUS",
  "Other")



for (i in ligrab_subdirs){
  subdir = paste0(lig_dir, i)
  if(!dir.exists(subdir)){dir.create(subdir)}
}




```

```{r}

# dem_ffn = paste0(dataroot, "GIS/Grid rasters - covariates/2021_DEM_LiDAR_Omakere_HBRC/merged.tif")
dem_ffn = paste0("D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/2021-07-10-LP0038-R_Hart/GIS/Grid rasters - covariates/2021_DEM_LiDAR_Omakere_HBRC/merged.tif")

file.exists(dem_ffn)

ligrg.allsteps(dem_ffn, lig_dir, dem_rsmpl_res = 5, focal_dist = 11, area_thresh = 5000)
  
  
```

# more work 12/10/2021

Check to see if the slope angle function in ligrab_utilities works

```{r}


source("D:/LUCA Team/Land Use Capability Assessments Limited/LUCA Directors - Documents/Code/RCode/ligrab/ligrab_utilities.R")

ffn = "D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/2021-07-10-LP0038-R_Hart/GIS/layers/elevation/DEM_resamp_5m.tif"


curv.and.slope.sum.ffout = paste0(dirname(ffn),"/curv.and.slope.sum.tif")

file.exists(ffn)

browser()

slope_ruleset = "D:/LUCA Team/Land Use Capability Assessments Limited/LUCA Directors - Documents/Code/RCode/ligrab/rulesets/GRASS_r-reclass_rules_SlopeAngle_HART.txt"

file.exists(slope_ruleset)

slopeangle.ff.out = ligrg.slopeangleclasses(ffn, slopeangleclass_ruleset = slope_ruleset)
r_slopeangle = raster(slopeangle.ff.out)
plot(r_slopeangle)


plancurv.ff.out = ligrg.curvatureclasses(ffn)
r_plancurv = raster(plancurv.ff.out)
plot(r_plancurv)


curv.and.slope = stack(r_slopeangle, r_plancurv)



curv.and.slope.sum = calc(curv.and.slope, sum)
plot(curv.and.slope.sum)


writeRaster(curv.and.slope.sum, curv.and.slope.sum.ffout, overwrite=T)

new = raster(curv.and.slope.sum.ffout)

library(mapview)
mapView(raster(curv.and.slope.sum.ffout))




ff.out = ligrg.aspectclasses(ffn)
plot(raster(ff.out))

dem_ffn = paste0("D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/2021-07-10-LP0038-R_Hart/GIS/Grid rasters - covariates/2021_DEM_LiDAR_Omakere_HBRC/merged.tif")

dem = raster(dem_ffn)

raster::crs(dem) <- "EPSG:4326"

```

# problem noted 22/10.2021 - none of the layers are being saved with their CRS

```{r}


library(raster)

# read thdem

DEM_ffn = "D:/LUCA Team/Land Use Capability Assessments Limited/LUCA team site - Documents/LUCA-A/Projects/2021-07-10-LP0038-R_Hart/GIS/layers/elevation/DEM_resamp_5m.tif"

r_DEM = raster(DEM_ffn)

crs(r_DEM) <- 2193
raster::crs(r_DEM) <- "EPSG:2193"



```

